### PR TITLE
Change `objectStoreNames` to DOMStringList

### LINKED ISSUE #101: `objectStoreNames`'s type seems wrong
https://github.com/jakearchibald/idb/blob/809a75ccc31c46ac62174ff9c2c10efffa5a53df/lib/entry.ts#L149

As far as I can tell, within my browser, this method returns a `DOMStringList`, which is *not* an array.

In particular, it contains a method `contains`, and does *not* contain array methods such as `indexOf`, which leads to both static and run-time errors.

### PR DESCRIPTION
**Pull request by NotWoods**
Add typed version of `DOMStringList` and use it as the type for `objectStoreNames`.

Fixes #101

### CODE REVIEW

File: lib/entry.ts [hunk 1]
```diff
@@ -140,13 +140,26 @@ type IDBPDatabaseExtends = Omit<
   'createObjectStore' | 'deleteObjectStore' | 'transaction' | 'objectStoreNames'
 >;
 
+/**
+ * A variation of DOMStringList with precise string types
+ */
+export interface TypedDOMStringList<
+  T extends string
+> extends DOMStringList {
+    readonly length: number;
```
Comment (jakearchibald) [inline lib/entry.ts]: Doesn't it already have this by extending `DOMStringList`?

File: lib/entry.ts [hunk 2]
```diff
@@ -140,13 +140,26 @@ type IDBPDatabaseExtends = Omit<
...
+    contains(string: T): boolean;
```
Comment (jakearchibald) [inline lib/entry.ts]: Do you think the type should be restricted to `T` here? Passing a different string doesn't feel like it should result in a type error.

File: lib/entry.ts (hunk 1 above)
Comment (NotWoods) [reply lib/entry.ts]: Yup, oops

File: lib/entry.ts (hunk 2 above)
Comment (NotWoods) [reply lib/entry.ts]: `.includes` for an array is also restricted to `T` so this stays consistent with it.

**Comment by jakearchibald** [comment]
Brilliant, thank you!
